---
title: "STAT525 HW5"
author: "Yuxuan Zhang"
date: "3/7/2020"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

###1
```{r}
library('Rlab')
y=c(-0.4, -1.4, 1.1, -0.3, 0.7, -0.1, 1.3, 0.3, 0.1, 1.2, 2.0, 0.9, -0.4, 0.9, 1.0)
w0 = 1
m = 10000
mu0 = 0
mu = matrix(0, nrow = m, ncol = 15)
weight = matrix(0, nrow = m, ncol = 15)
for (i in 1:m) {
  for (j in 1:15) {
    if (rbinom(1, 1, 0.9) == 1){
      if (j == 1) {
        mu[i,j] = 0
      } else {
        mu[i,j] = mu[i,j-1]
      }
    } else {
      mu[i,j] = rnorm(1, mean = 0, sd = 1)
    }
    
    if (j == 1){
      weight[i,j] = dnorm(y[j], mean = mu[i,j], sd=1)
    } else {
      weight[i,j] = weight[i,j-1]* dnorm(y[j], mean = mu[i,j], sd=1)
    }
    
  }
}
w_sum = apply(weight, 2, sum)
mean = apply(mu*weight,2, sum)/w_sum
mean
```

###2
The variance of $X(b^*)$ is smaller than the variance I obtained earlier for estimating $E(\frac{1}{1+X^3})$ with Naive Monte Carlo method.
```{r}
x = runif(1000)
b = cov(1/(1+x^3),(1+x^3))/var(1+x^3)
xb = 1/(1+x^3)-b*(1+x^3-5/4)
# MEAN OF THE OF Xb
mean(xb)
# VARIANCE OF Xb
var(xb) / 1000
# Variance OF ESTIMATE BY NAIVE MONTE CARLO
var(1/(1+x^3)) / 1000
```

### 3
$$f(x) = 160x^{-6}, 2\leq x \leq \infty$$
The inverse CDF is given by
$$g(u) = F^{-1}(u) = 2(1-u)^{-1/5}, 0 \leq x \leq 1$$
g is monotonic function, $X=g(U), X'=g(1-U)$ and $U1,U2$ are independent uniform random variables, we have
$$E(\{g(U1)-g(U2)\}\{g(1-U1)-g(1-U2)\}) = 2Cov(X,X') \leq 0$$

Thus, $Var((X+X')/2) \leq Var(X)/2$
```{r}
u = runif(1000)
x = 2*(1-u)^(-1/5)
x2 = 2*(u)^(-1/5)
mean(x)
var(x) / 1000
mean((x+x2)/2)
var((x+x2)/2) / 1000
```